name: Lint Code

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        env:
          GH_SHAREDLIB_PAT: ${{secrets.GH_SHAREDLIB_PAT}}
      - name: Run lint
        run: npm run lint
        env:
          GH_SHAREDLIB_PAT: ${{secrets.GH_SHAREDLIB_PAT}}
